### ISSUE TITLE
sealedSenderDecryptMessage should call groupDecrypt internally

### ISSUE THREAD

**Issue by indutny-signal** [signalapp/libsignal#347]
It is weird that `sealedSenderMultiRecipientEncrypt` seals the message, but `sealedSenderDecryptMessage` is not capable of decrypting it and we have to resort to `sealedSenderDecryptToUsmc` and `groupDecrypt` instead of one call.

**Comment by jrose-signal** [comment]
`sealedSenderMultiRecipientEncrypt` isn't doing group encryption, though (or any ratcheting encryption); it parallels `sealedSenderDecryptToUsmc` much more than `sealedSenderDecryptMessage`.

It does seem like we should have a decrypt-to-plaintext API, and the simplest way to do that would be to add a SenderKeyStore parameter to `sealedSenderDecryptMessage`, but I'm not sure that's the *best* API to have long-term. If we compare with the Java API:

- Instead of many different stores, there's a single SignalProtocolStore that gets passed to most methods, including the equivalent of `sealedSenderDecryptMessage`.
- When the message inside a sealed sender message fails to decrypt, there's still important information about the supposed sender, group, and content hint that need to be returned to the caller. Of course we can do that through structured errors; it's just additional work.

I do think these are the right way to go, but it'd mean changing the API surface as well as the implementation, which means work from Desktop (and iOS, for consistency) as well as for libsignal-client itself.

**Comment by jrose-signal** [comment]
More discussion in #494 (I forgot we had this issue already).
