### ISSUE TITLE
Swift: Fingerprint API 

### ISSUE THREAD

**Issue by omaarr90** [signalapp/libsignal#353]
I tried to use the `Fingerprint.swift` class but I've hit a dead end. 

I was able to generate Fingerprint and use the displayable format and scannable format. 

Displayable format works as expected. both numbers match. However, when I try to use Scannable Format, I was unable to do so. 

`ScannableFingerprint` has a method called compare which takes another `ScannableFingerprint` but since the initializer is marked as `ScannableFingerprint` there is no way to initialize this class and use the method compare.

I assume the scannable format is initialized after scanning the QRCode and compared with ScannableFingerprint of the user scanning.

**Comment by jrose-signal** [comment]
Oooops, thank you! That's what we get for still using the old implementation in the actual iOS app, this was exposed because Android is already using it and we figured iOS would eventually switch over. I'll leave this issue open until we can get the time to verify that this is actually the API iOS would like to use.
