### ISSUE TITLE
[Feature Request] Use of LibSignal outside of Signal

### ISSUE THREAD

**Issue by abdokhe** [signalapp/libsignal#533]
I would appreciate If there was a public crate in rust or a package for node or Java that can be used Outside of signal with full documentation, it will help in securing a lot of application I tried to make my own implementation of signal encryption but there were a lot of problems, just building this Lib crashes a lot, it will be really helpful to export this library to the use outside of signal,
and I would for sure contribute to it.
and please could you share some graphs explaining how the encryption process works how to store the keys safely. 

Thanks in advance for the answer.

**Comment by alanliu-signal** [comment]
Unfortunately, it is currently not a primary goal of LibSignal to provide a public crate/package for integration with other applications, due to prioritization and resourcing.  We will revisit that in the future as time permits.

In the meantime, we provide documentation on how the Signal encryption protocol works here [https://signal.org/docs/].  It is the responsibility of the application to ensure that keys are stored safely, and outside the scope of the protocol itself.

As for problems and crashes, are you trying to build something other than the rust crates? We’re not aware of any crashes with the build process.  Please open a new issue if there are specific build failures that shouldn't be happening.
