### ISSUE TITLE
SHA1PRNG forced in SecureRandom

### ISSUE THREAD

**Issue by nicolasbon38** [signalapp/libsignal#558]
In the [KeyHelper](https://github.com/signalapp/libsignal/blob/main/java/shared/java/org/signal/libsignal/protocol/util/KeyHelper.java#L30) class, an instance of SecureRandom is created and "SHA1PRNG" is passed to the constructor.

Why did you do this choice ? Wouldn't calling the constructor without argument to let the best PRNG on a given platform to be picked ?

**Comment by jrose-signal** [comment]
Excitingly, that code is [over ten years old](https://github.com/signalapp/libsignal-protocol-java/blame/fde96d22004f32a391554e4991e4e1f0a14c2d50/java/src/main/java/org/whispersystems/libsignal/util/KeyHelper.java#L53)! Well before my time at Signal, and before I did anything with Android.

Given that we use the default SecureRandom elsewhere in libsignal, it would make sense to do the same here. There isn't even a performance argument, since registration IDs are only generated at registration and when you change your number.

**Comment by jrose-signal** [comment]
Ha, I accidentally autoclosed this with the fix in the private pre-release repo. The hardcoding of SHA1PRNG will be removed in the next release of libsignal, thanks for calling it out!
