### ISSUE TITLE
nightly builds fail due to curve25519-dalek

### ISSUE THREAD

**Issue by saman3d** [signalapp/libsignal#575]
due to this issue [Build fails on nightly-2024-02-05](https://github.com/dalek-cryptography/curve25519-dalek/issues/618) dalek builds started to fail on nightly 2024-02-05. 

they released a new patch version fixing this issue.
pr: [Fix nightly build](https://github.com/dalek-cryptography/curve25519-dalek/pull/619)
tag: [4.1.2](https://github.com/dalek-cryptography/curve25519-dalek/releases/tag/curve25519-4.1.2)

please update curve25519-dalek dependency version

**Comment by saman3d** [comment]
I need to build my project with the new rust nightly version. can I open a pr for this issue?

**Comment by jrose-signal** [comment]
We're discussing what to do about 4.1.2 not passing its own CI tests on nightly (because new warnings have been introduced). Upstream has fixes for that as well, but they're not in an actual tag yet.

Note that you don't need to use Signal's fork of curve25519-dalek unless you're using zkgroup. The other crates can use the normal upstream version.

**Comment by jrose-signal** [comment]
(Update: we asked the dalek folks for a new tag, they haven't committed to one yet.)

**Comment by jrose-signal** [comment]
Included in v0.51.1, using curve25519-dalek v4.1.3!
