### ISSUE TITLE
Tests valid_simple_chat_update_message_{binproto,jsonproto,serialize} failing

### ISSUE THREAD

**Issue by Marcool04** [signalapp/libsignal#587]
Hi there,

I maintain the AUR package for libsignal-ffi https://aur.archlinux.org/packages/libsignal-ffi which is used for building mautrix-signal which I also maintain the AUR package for: https://aur.archlinux.org/packages/mautrix-signal. I am trying to update the PKGBUILD to 0.55.1, and after solving the problem described in https://github.com/signalapp/libsignal/issues/583 I am now seeing test failures:

```
failures:
    valid_simple_chat_update_message_binproto
    valid_simple_chat_update_message_jsonproto
    valid_simple_chat_update_message_serialize
```

The full log of the test run is here: https://termbin.com/9pgk

I am building this in a clean, up to date, arch linux chroot, and apart from some unused import errors the build process went ok.

Please let me know if you need any more information to help debug this, or if you think there is a problem on my end. Any help will be much appreciated.

Regards,
Mark.

**Comment by jrose-signal** [comment]
It sounds like you didn't get the revision of https://github.com/signalapp/Signal-Message-Backup-Tests/ referenced from v0.55.1, but instead took the latest. The message backup feature isn't stable yet, so there's still a lot of churn.

Since you're not using it (\*stare\*), one option would be to explicitly skip the libsignal-message-backup package when testing, but otherwise be careful to get the correct submodule version when flattening into your downstream repo!

**Comment by Marcool04** [comment]
Oh you're quite right! My mistake of course 🤦‍♂️ I didn't look carefully enough when integrating the test repo. Thanks for taking the time to respond and for your help! 👍️
