### ISSUE TITLE
use non-mut reference in load_sender_key

### ISSUE THREAD

**Issue by 2ob** [signalapp/libsignal#86]
`SenderKeyStore::load_sender_key` should not need a _mutable_ reference to `self`.

https://github.com/signalapp/libsignal-client/blob/4bee29760a14e08e1e87642b3db130961af07fd9/rust/protocol/src/storage/traits.rs#L103-L104

**Comment by jack-signal** [comment]
Thanks for pointing this out. We probably need to figure out what our story is here, because IMO actually all of the storage traits should be `&mut self` since we have no idea how they are implemented, eg using a non-serialized database connection.

That said currently we use just `&self` for other operations which are nominally read-only, so we should either switch that to `&self` or switch everything to `&mut self`
